name: task_news
description: "task_news"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-325.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  carousel_slider: ^4.2.1
  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: OpenSans
      fonts:
        - asset: lib/assets/font/opensans/OpenSans-Medium.ttf
    - family: OpenSansItalic
      fonts:
        - asset: lib/assets/font/opensans/OpenSans-LightItalic.ttf    
